# Generated by Django 4.1.4 on 2023-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=100)),
                ("emp_age", models.IntegerField()),
            ],
        ),
    ]
